/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(auth)/forgot-password': RouteRecordInfo<'/(auth)/forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/(auth)/login': RouteRecordInfo<'/(auth)/login', '/login', Record<never, never>, Record<never, never>>,
    '/(auth)/register': RouteRecordInfo<'/(auth)/register', '/register', Record<never, never>, Record<never, never>>,
    '/(root)/': RouteRecordInfo<'/(root)/', '/', Record<never, never>, Record<never, never>>,
    '/(root)/about': RouteRecordInfo<'/(root)/about', '/about', Record<never, never>, Record<never, never>>,
    '/(root)/s/': RouteRecordInfo<'/(root)/s/', '/s', Record<never, never>, Record<never, never>>,
    '/(root)/s/[code]': RouteRecordInfo<'/(root)/s/[code]', '/s/:code', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    '/(dashboard)/dashboard/': RouteRecordInfo<'/(dashboard)/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/(dashboard)/respondents/': RouteRecordInfo<'/(dashboard)/respondents/', '/respondents', Record<never, never>, Record<never, never>>,
    '/(dashboard)/respondents/[id]': RouteRecordInfo<'/(dashboard)/respondents/[id]', '/respondents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(dashboard)/settings/': RouteRecordInfo<'/(dashboard)/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/(dashboard)/settings/account': RouteRecordInfo<'/(dashboard)/settings/account', '/settings/account', Record<never, never>, Record<never, never>>,
    '/(dashboard)/settings/billing/': RouteRecordInfo<'/(dashboard)/settings/billing/', '/settings/billing', Record<never, never>, Record<never, never>>,
    '/(dashboard)/survey/': RouteRecordInfo<'/(dashboard)/survey/', '/survey', Record<never, never>, Record<never, never>>,
    '/(dashboard)/survey/[code]': RouteRecordInfo<'/(dashboard)/survey/[code]', '/survey/:code', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    '/(dashboard)/survey/add': RouteRecordInfo<'/(dashboard)/survey/add', '/survey/add', Record<never, never>, Record<never, never>>,
    '/(dashboard)/survey/edit/[code]': RouteRecordInfo<'/(dashboard)/survey/edit/[code]', '/survey/edit/:code', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    '/(dashboard)/user/': RouteRecordInfo<'/(dashboard)/user/', '/user', Record<never, never>, Record<never, never>>,
    '/(dashboard)/user/[id]': RouteRecordInfo<'/(dashboard)/user/[id]', '/user/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(dashboard)/user/edit/[id]': RouteRecordInfo<'/(dashboard)/user/edit/[id]', '/user/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
