# Generated by Django 5.1.7 on 2025-03-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='limit',
            field=models.IntegerField(default=5),
        ),
    ]
