# Generated by Django 5.1.7 on 2025-03-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
