# Generated by Django 5.1.7 on 2025-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survey_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
