# Generated by Django 5.1.7 on 2025-03-17 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kabupaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabupaten', models.CharField(max_length=10)),
                ('nama_kabupaten', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geom', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Kabupaten',
                'verbose_name_plural': 'Daftar Kabupaten',
                'ordering': ['nama_kabupaten'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=10)),
                ('nama_provinsi', models.CharField(max_length=100)),
                ('provinsi_singkat', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latitude2', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude2', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geom', models.JSONField(null=True)),
                ('line_geom', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Daftar Provinsi',
                'ordering': ['-nama_provinsi'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(max_length=10)),
                ('nama_kecamatan', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geom', models.JSONField(null=True)),
                ('kabupaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.kabupaten')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Daftar Kecamatan',
                'ordering': ['nama_kecamatan'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='images/avatar.png', upload_to='avatars')),
                ('visible_password', models.TextField(blank=True, max_length=255, null=True, verbose_name='visible_password')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile User',
                'verbose_name_plural': 'Daftar Profile User',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.provinsi'),
        ),
        migrations.CreateModel(
            name='desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilayah', models.CharField(max_length=255)),
                ('nama_desa', models.CharField(max_length=100)),
                ('nama_kecamatan', models.CharField(max_length=100)),
                ('nama_kabupaten', models.CharField(max_length=100)),
                ('nama_provinsi', models.CharField(max_length=100)),
                ('desa', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.kabupaten')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.kecamatan')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.provinsi')),
            ],
            options={
                'verbose_name': 'Desa',
                'verbose_name_plural': 'Daftar Desa',
                'ordering': ['-id'],
            },
        ),
    ]
