# Generated by Django 5.1.7 on 2025-03-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='auth_user_profile',
        ),
    ]
