# Generated by Django 5.1.7 on 2025-03-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_profile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
